// +--------------------------------------------------------------------------------+
// | Repository: https://github.com/Joseph-kaku/macawmanager                        |                                                                       
// | Created for BYU-I Web Services Course.                                         |
// +--------------------------------------------------------------------------------+
// | This module was programmed by Nicole Fluckiger, Jospeh Kaku, and Ryker Swensen |
// +--------------------------------------------------------------------------------|
// | File Version 1.4                                                               |
// +--------------------------------------------------------------------------------+
// | CODE DESCRIPTION                                                               |
// | .rest file for completed projects rest request testing.                        |
// |                                                                                |
// +--------------------------------------------------------------------------------+
// | NOTES                                                                          |
// | Please be sure to update files with comments so we can help eachother with this|
// | team assignment. Please comment any issues, bugs, or successes to help each of |
// | of us learn. Thanks, - Ryker.                                                  |
// |                                                                                |
// \-------------------------------------------------------------------------------*/


// +--------------------------------------------------------------------------------+
// | Local Host!                                                                    |
// +--------------------------------------------------------------------------------+
// Get All Completed Projects
GET http://localhost:8080/completedprojects/ HTTP/1.1

### Get Completed Project by Project ID
GET http://localhost:8080/completedprojects/655599e91fe3a853a6d85891/ HTTP/1.1

### Post Completed Project
POST http://localhost:8080/completedprojects HTTP/1.1
content-type: application/json

{
    "projectName": "Web Application for final presentation",
    "projectDescription": "Design and develop a user-friendly e-commerce platform with advanced features and functionalities.",
    "technologies": [
        "C++",
        "C#",
        "MongoDB",
        "Express.js"
    ],
    "completionDate": "2023-10-04",
    "projectManager": "Ryker Swensen"
}

### Put Completed Project
PUT http://localhost:8080/completedprojects/656bd8964f8036da51f01d10 HTTP/1.1   
content-type: application/json

{
    "projectName": "Updated Web Application for final presentation",
    "projectDescription": "Design and develop a user-friendly e-commerce platform with advanced features and functionalities.",
    "technologies": [
        "C++",
        "C#",
        "MongoDB",
        "Express.js"
    ],
    "completionDate": "2023-10-04",
    "projectManager": "Ryker Swensen"
}

### Delete Completed Project
DELETE http://localhost:8080/completedprojects/656bd8964f8036da51f01d10 HTTP/1.1


// +--------------------------------------------------------------------------------+
// | Render!                                                                        |
// +--------------------------------------------------------------------------------|

### Get All Completed Projects
GET https://macawmanager.onrender.com/completedprojects HTTP/1.1

### Get Completed Project by Project ID
GET https://macawmanager.onrender.com/completedprojects/655599e91fe3a853a6d85891/ HTTP/1.1

### Post Completed Project
POST https://macawmanager.onrender.com/completedprojects/ HTTP/1.1
content-type: application/json

{
    "projectName": "Web Application Development for Wendy's Fast Food Chain",
    "projectDescription": "Design and develop a user-friendly e-commerce platform with advanced features and functionalities.",
    "technologies": [
        "C++",
        "C#",
        "MongoDB",
        "Express.js"
    ],
    "completionDate": "2023-10-04",
    "projectManager": "Ryker Swensen"
}

### Put Completed Project
PUT https://macawmanager.onrender.com/completedprojects/655d6de2e9166f72183db64b HTTP/1.1
content-type: application/json

{
    "projectName": "Web Application Development for people",
    "projectDescription": "Design and develop a user-friendly e-commerce platform with advanced features and functionalities.",
    "technologies": [
        "C++",
        "C#",
        "MongoDB",
        "Express.js"
    ],
    "completionDate": "2023-10-04",
    "projectManager": "Ryker Swensen"
}

### Delete Completed Project
DELETE https://macawmanager.onrender.com/completedprojects/655d6de2e9166f72183db64b HTTP/1.1